upstreams:
  - id: 1
    nodes:
      "jaeger:16686": 1
  - id: 2
    nodes:
      "catalog:8080": 1
  - id: 3
    nodes:
      "pricing:8000": 1

routes:
  - name: Product Catalog
    uri: /products*
    upstream_id: 2
  - name: Prices
    uri: /prices*
    upstream_id: 3
  - uris:
    - /search
    - /api/*
    - /static/*
    - /dependencies
    - /trace/*
    - /monitor
    upstream_id: 1
    plugins:
      opentelemetry: null
  - uri: /
    upstream_id: 1
    plugins:
      opentelemetry: null
      redirect:
        uri: /search
        ret_code: 301

global_rules:
  - id: 1
    plugins:
      opentelemetry:
        sampler:
          name: always_on
        additional_attributes:
          - http_x-otel-key
          - remote_addr
#END
